name: Deploy Web App to EC2

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
    paths:
      - 'web_app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Create .env file
        working-directory: web_app
        run: echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}" > .env

      - name: Install dependencies
        working-directory: web_app
        run: npm install

      - name: Build frontend
        working-directory: web_app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp-build
          path: web_app/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: webapp-build
          path: /tmp/webapp

      - name: Copy production files to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          scp -r -o StrictHostKeyChecking=no -i private_key.pem /tmp/webapp/* $EC2_USER@$EC2_HOST:/tmp/webapp/

      - name: Deploy to EC2 and reload NGINX
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            sudo mkdir -p /var/www/myreactapp
            sudo rm -rf /var/www/myreactapp/*
            
            sudo cp -r /tmp/webapp/* /var/www/myreactapp/
            sudo chown -R www-data:www-data /var/www/myreactapp
            sudo rm -rf /tmp/webapp

            sudo systemctl reload nginx
          EOF
